name: Strace Logger
description: Runs a command with strace capturing all file accesses

inputs:
  command:
    description: "The full command to run (e.g., ./ci-script.sh)"
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y strace
        mkdir -p strace_logs

        logfile="strace_logs/trace_$(date +%s).log"
        echo "📦 Running under strace. Logging to $logfile"

        # Wrap command under strace
        strace -f -tt -e trace=file -o "$logfile" bash -c "${{ inputs.command }}"
    
    - uses: actions/upload-artifact@v3
      with:
        name: strace-logs
        path: strace_logs/