name: Setup strace logging
description: Log every shell command with strace
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        mkdir -p ci-bin strace_logs
        cat <<'EOF' > ci-bin/bash
        #!/bin/bash
        set -e
        cmd_hash=$(echo "$@" | sha1sum | awk '{print $1}')
        mkdir -p strace_logs
        exec strace -tt -f -o strace_logs/step_${cmd_hash}.log /bin/bash "$@"
        EOF
        chmod +x ci-bin/bash
        echo "PATH=$GITHUB_WORKSPACE/ci-bin:$PATH" >> "$GITHUB_ENV"