name: 'Universal Strace'
description: 'Attach strace to every child process in this job'
inputs:
  outdir:
    description: 'Directory to write .log files'
    default: 'strace-logs'
runs:
  steps:
    - name: Install strace
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y strace

    - name: Prepare output dir
      shell: bash
      run: mkdir -p ${{ inputs.outdir }}

    - name: Launch strace daemon
      shell: bash
      run: |
        # Lower ptrace_scope so root can attach to spawned procs
        echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope >/dev/null

        # Background loop: every second, attach strace to brand-new children
        (
          prev_pids=""
          while true; do
            # list all processes in this session (same SID as this shell)
            pids=$(ps -o pid,ppid,sid -e | awk -v sid=$(ps -o sid= $$) \
                   '$3==sid { print $1 }')

            for pid in $pids; do
              # only attach once per PID and skip ourself & strace procs
              if [[ "$prev_pids" != *" $pid "* ]] && \
                 ! ps -p $pid -o cmd= | grep -qE 'strace|bash'; then

                sudo strace \
                  -ff \
                  -e trace=file,execve \
                  -p $pid \
                  -o ${{ inputs.outdir }}/strace-$pid.log \
                  </dev/null &

                prev_pids="$prev_pids $pid"
              fi
            done

            sleep 1
          done
        ) &

    - name: Export output dir
      shell: bash
      run: echo "STRACE_OUT=${{ inputs.outdir }}" >> $GITHUB_ENV
