name: Setup Strace Wrapper Shell
description: Replaces bash shell with strace-wrapped shell for CI logging

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        mkdir -p ci-bin strace_logs

        cat << 'EOF' > ci-bin/bash
        #!/bin/bash
        set -e

        cmd_hash=$(echo "$@" | sha1sum | cut -d ' ' -f1)
        logfile="strace_logs/step_${cmd_hash}.log"

        echo "🌀 Running under strace: $@" >> strace_logs/bash_calls.log

        # Run the command with strace
        sudo -E strace -f -tt -e trace=file -o "$logfile" /bin/bash "$@"
        EOF

        chmod +x ci-bin/bash
        echo "$GITHUB_WORKSPACE/ci-bin" >> $GITHUB_PATH
