name: File Access Logger
description: Logs all file accesses during a command
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y inotify-tools
        mkdir -p file_access_logs
        inotifywait -m -r . \
          -e open,access,modify,close_write,move,create,delete \
          --format '%T %w%f %e' --timefmt '%Y-%m-%d %H:%M:%S' \
          > file_access_logs/inotify.log &
        echo $! > file_access_logs/inotify.pid

    - shell: bash
      run: |
        echo "▶️ Running: ${{ inputs.command }}"
        eval "${{ inputs.command }}"

    - shell: bash
      run: |
        kill $(cat file_access_logs/inotify.pid)
        sleep 1

    - uses: actions/upload-artifact@v4
      with:
        name: file-access-logs
        path: file_access_logs/inotify.log

inputs:
  command:
    description: "The command to run"
    required: true